function save_to_table(Planets)
file_PT_planets = fopen('PT_Planets.tex','w');
write_table_header(file_PT_planets,'table:SfPlanets');
Earth = Planets(1); % kluge
for ij = 1:6
	if Planets(ij).z_cracking_1mm_m
		write_table_line(Planets(ij),file_PT_planets,Earth);
	end
end
fprintf(file_PT_planets,'%s\n','\hline');
for ij = 7:length(Planets)
	if Planets(ij).z_cracking_1mm_m
		write_table_line(Planets(ij),file_PT_planets,Earth);
	end
end
fprintf(file_PT_planets,'%s\n%s\n%s\n%s\n%s\n',...
    '\hline',...
     '\end{tabular}',...
    '\end{centering}',...
    '\caption{Parameters for potential ocean planets in the outer solar system, after \citet{Hussmann2006}}',...
    '\end{table*}');
fclose(file_PT_planets);
%==========================================================================
function write_table_header(fid,table_label)
    global PLOT_H2
    if ~PLOT_H2
        t_label = [' \begin{table*}[f]\label{' table_label  '}'];
        fprintf(fid,'%s\n%s\n%s\n%s\n%s\n%s\n',...
        t_label,...
       '\begin{centering}',...
       '\begin{tabular}{|c|c|r@{.}l|r@{.}l|c|c|c|c|c|c|}',...
       '\hline ',...
       '    & $R_{P}$   & \multicolumn{2}{c}{$M_{P}$ }                       \vline& \multicolumn{2}{c}{$H$}                      \vline  & $d$       &   $T_{o}$  &   $T_{z}$   & $P_{z}$  & \textbf{$z$} \\ ',...
       '    & (km)      &         \multicolumn{2}{c}{($\times 10^{20}$ kg)}  \vline& \multicolumn{2}{c}{($\times 10^{9}$ W) }  \vline  & (km)              & ($^{o}$C)        &  ($^{o}$C)   & (MPa)   & \textbf{(km)}\\ ',...
       '\hline \hline');
    elseif PLOT_H2
        t_label = [' \begin{table*}[f]\label{' table_label  '}'];
        fprintf(fid,'%s\n%s\n%s\n%s\n%s\n%s\n',...
        t_label,...
       '\begin{centering}',...
       '\begin{tabular}{|c|c|r@{.}l|c|c|c|c|c|r@{.}l|r@{.}l|r@{.}l|c|c|}',...
       '\hline ',...
       '    & $R_{P}$   & \multicolumn{2}{c}{$M_{P}$ }                       \vline & $d$       &   $T_{o}$  &   $T_{z}$   & $P_{z}$  & $z$ & \multicolumn{2}{c}{$dz/dt$} \vline & \multicolumn{2}{c}{$H_{rad}$} \vline  & \multicolumn{2}{c}{$\frac{H_{serp}}{H_{rad}}$} \vline & \multicolumn{2}{c}{$F_{H_{2}}$} \\ ',...
       '    & (km)      &         \multicolumn{2}{c}{($\times 10^{20}$ kg)}  \vline & (km)              & ($^{o}$C)        &  ($^{o}$C)   & (MPa)   & (km) & \multicolumn{2}{c}{($\frac{\mu m}{yr}$)}\vline&\multicolumn{2}{c}{($\frac{mW}{m^{2}}$)} \vline& \multicolumn{2}{c}{(\%)} \vline  & ($\frac{F}{F_{\earth}}$) \vline &(Tmol~yr$^{-1}$)\\ ',...
       '\hline \hline');
    end
%        '    & $R_{P}$   & \multicolumn{2}{c}{$M_{P}$ }                       \vline & $d$       &   $T_{o}$  &   $T_{z}$   & $P_{z}$  & $z$ & \multicolumn{2}{c}{$dz/dt$} \vline & \multicolumn{2}{c}{$H_{rad}$} \vline  & \multicolumn{2}{c}{$\frac{H_{serp}}{H_{rad}}$} \vline & \multicolumn{2}{c}{$F_{H_{2}}$} \\ ',..
%        '    & (km)      &         \multicolumn{2}{c}{($\times 10^{20}$ kg)}  \vline & (km)              & ($^{o}$C)        &  ($^{o}$C)   & (MPa)   & (km) & \multicolumn{2}{c}{$\log_{10}(\frac{mm}{yr})$}\vline&\multicolumn{2}{c}{($\frac{mW}{m^{2}}$)} \vline& \multicolumn{2}{c}{(\%)} \vline  & ($\frac{F}{F_{\earth}}$) \vline &(Tmol~yr$^{-1}$)\\ ',...

%==========================================================================
function write_table_line(Planet,fid,Earth)
    global PLOT_H2
if ~PLOT_H2 & (Planet.z_cracking_1mm_m>0) % this table is for the paper on cracking depths in extraterrestrial seafloors
    fprintf(fid,'%s\t&\t%0.0f\t&\t%s\t&\t%s\t&\t%0.0f\t&\t%0.0f\t&\t%0.0f\t&\t%0.0f\t&\t\\textbf{%0.0f}\\\\ \n',...
        Planet.name, ...
        Planet.R_m/1e3, ...
        num2tex(Planet.M_kg/1e20,'%0.2f'),...
        num2tex(Planet.H_W/1e9,'%0.2f'),...
        (Planet.d_ocean_km),...
        (Planet.T_oC(1)),...
        (Planet.T_z_1mm_oC),...
        (Planet.P_z_1mm_MPa),...
        (Planet.z_cracking_1mm_m/1e3));
elseif PLOT_H2 % this table is for the paper on heat in extraterrestrial oceans
    Planet.name
    fprintf(fid,'%s\t&\t%0.0f\t&\t%s\t&\t%0.0f\t&\t%0.0f\t&\t%0.0f\t&\t%0.0f\t&\t%0.0f\t&\t%s\t&\t%s\t&\t%s\t&\t%0.0f&\t%s\\\\ \n',...
        Planet.name, ...
        Planet.R_m/1e3, ...
        num2tex(Planet.M_kg/1e20,'%0.2f'),...
        (Planet.d_ocean_km),...
        (Planet.T_oC(1)),...
        (Planet.T_z_1mm_oC(1)),...
        (Planet.P_z_1mm_MPa(1)),...
        (Planet.z_cracking_1mm_m(1)/1e3),...
		num2tex(Planet.dzdt_mm_yr(1)*1e3,'%0.3f'),...
        num2tex(Planet.F_rad_W_m2(1)*1e3,'%0.2f'),...
        num2tex(mean(Planet.F_serp_W_m2./Planet.F_rad_W_m2*100),'%0.2f'),...% previously -->  num2tex(Planet.mean_F_serp_W_m2*1e3,'%0.3f')
        Planet.mean_FH2_molecules_cm2_s/Earth.mean_FH2_molecules_cm2_s,...%  previously --> Planet.mean_FH2_molecules_cm2_s/1e9);
        num2tex(Planet.mean_FH2_molecules_cm2_s*3.15576e7*4*pi*Planet.R_m^2*1e4/6.022e23/1e12,'%0.3f'));%  previously --> Planet.mean_FH2_molecules_cm2_s/1e9); % added 2/9/15
end
